### ISSUE TITLE
Bootstrap-4 Select Widget `name` is not defined

### ISSUE THREAD

**Issue by sasikanth513** [rjsf-team/react-jsonschema-form#2011]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

I'm getting the following error while using `SelectWidget` using `bootstrap-4` theme

```
ERROR	Unhandled error during request: ReferenceError: name is not defined
    at SelectWidget (/var/task/node_modules/@rjsf/bootstrap-4/dist/bootstrap-4.cjs.production.min.js:1:11911)
    at d (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Object.renderPage (/var/task/node_modules/next/dist/next-server/server/render.js:45:686)
    at Function.getInitialProps (/var/task/.next/serverless/pages/widget/[slug].js:1549:19)
    at loadGetInitialProps (/var/task/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:45:977)
```

This is happening because of this line https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/bootstrap-4/src/SelectWidget/SelectWidget.tsx#L87

Here we are using `name` field which is not passed to this widget.

If I check the `SelectWidget` code for `core` ui, there is no mention of `name` property.

If I remove this line from my local code, everything is working fine.
Happy to raise a PR to remove this line of code when someone confirms this.

### Steps to Reproduce

1. Create repo with `bootstrap-4`
2. Use the following property in your schema
```
		alignment: {
          type: "string",
          title: "Alignment",
          enum: [ "left", "right", "stretch" ],
          enumNames: [ "Left", "Right", "Stretch" ]
        }
```
3. In your terminal you'll see the above error

#### Expected behavior

Everything should work fine without any errors

#### Actual behavior

Seeing an error in my terminal

### Version

```
    "@rjsf/bootstrap-4": "^2.3.0",
    "@rjsf/core": "^2.3.0",
    "bootstrap": "^4.5.2",
    "next": "9.5.1",
    "react": "16.13.1",
    "react-bootstrap": "^1.3.0",
    "react-dom": "16.13.1"
```

**Comment by epicfaace** [comment]
@anikethsaha @Xtremilicious could one of you look into this if you get a chance?

**Comment by Xtremilicious** [comment]
@epicfaace The PR above should address this issue. Cheers :)
