### ISSUE TITLE
Unable to pass a boolean input to readOnly (@rjsf/bootstrap-4)

### ISSUE THREAD

**Issue by gpop3** [rjsf-team/react-jsonschema-form#2259]
### Prerequisites
* [x]  I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
* [x]  In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
* [x]  Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

Cannot pass a boolean input to readOnly with de Bootstrap4 theme but it is possible with MaterialUI theme.

#### Imports

``` typescript
import React from "react";
import { Theme as Bootstrap4Theme } from "@rjsf/bootstrap-4";
import {
  withTheme
} from "@rjsf/core";
```

#### Code

``` typescript
  const JsonSchemaForm = withTheme(Bootstrap4Theme);
  return (
    <div style={{ position: "relative" }}>
      <JsonSchemaForm
	schema={{
 	 "title": "Entité",
	  "type": "object",
	  "properties": {
	    "@id": {
	      "type": "string",
 	     "title":"ID"
  	  },
  	  "nom": {
   	   "type": "string",
 	     "title":"Nom"
  	  },
  	  "prenom": {
  	    "type": "string"
  	  },
  	  "email": {
  	    "type": "string"
  	  },
   	 "age": {
   	   "type": "number"
  	  },
  	  "sdf": {
 	     "type": "boolean"
 	   }
	  },
	  "required": ["@id", "nom", "prenom", "email", "age", "sdf"]
	}}
        uiSchema={ {
          nom: {"ui:readonly": true},
          sdf: {"ui:readonly": true}
        }
        }
      />
      </JsonSchemaForm>
  );
```

#### Expected behavior

Have the input read only as the MaterialUI theme
Screenshot (materialUI theme):
![image](https://user-images.githubusercontent.com/72933545/109641758-5d6ea880-7b52-11eb-937e-41e142e7fe91.png)

#### Actual behavior

Simple boolean input
Screenshot (bootstrap theme)
![image](https://user-images.githubusercontent.com/72933545/109641487-0cf74b00-7b52-11eb-913e-370032deee19.png)

### Version

"@rjsf/bootstrap-4": "^2.4.2"
"@rjsf/core": "^2.3.0"
"@rjsf/material-ui": "^2.3.0"

**Comment by HarmonicTons** [comment]
A live playground showing this behavior:

https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJjaGVjayI6ZmFsc2V9LCJzY2hlbWEiOnsidGl0bGUiOiJSZWFkb25seSBjaGVja2JveCBub3Qgd29ya2luZyB3aXRoICdib290c3RyYXAtNCciLCJkZXNjcmlwdGlvbiI6IkNoYW5nZSB0aGUgdGhlbWUgdG8gJ2RlZmF1bHQnIG9yICdib290c3RyYXAtNCciLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJjaGVjayI6eyJ0aXRsZSI6Ijw9IENhbiBiZSBjaGVja2VkIHdpdGggYm9vdHN0cmFwLTQgZXZlbiB3aXRoIHVpOnJlYWRvbmx5IiwidHlwZSI6ImJvb2xlYW4ifX19LCJ1aVNjaGVtYSI6eyJjaGVjayI6eyJ1aTpyZWFkb25seSI6dHJ1ZX19LCJ0aGVtZSI6ImJvb3RzdHJhcC00IiwibGl2ZVNldHRpbmdzIjp7InZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2V9fQ==

**Comment by HarmonicTons** [comment]
The issue seems to be quite simple: In the bootstrap-4 Checkbox Widget we define a property `readOnly` on the react-bootstrap Form.Check component:

https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/bootstrap-4/src/CheckboxWidget/CheckboxWidget.tsx#L40

... but there is no such property for that component according to:

https://react-bootstrap.github.io/components/forms/#forms-form-check

So the solution should be something like:

```ts
        <Form.Check
          id={id}
          label={desc}
          checked={typeof value === "undefined" ? false : value}
          required={required}
          disabled={disabled || readonly}
          autoFocus={autofocus}
          onChange={_onChange}
          type="checkbox"
          onBlur={_onBlur}
          onFocus={_onFocus}
        />
```

I would submit a PR but I cannot start a fresh install of the project on a cloud based dev env (gitpod): build fail with:

```
@rjsf/material-ui: (typescript) Error: /workspace/react-jsonschema-form/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx(39,7): semantic error TS2322: Type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7' is not assignable to type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7'.
@rjsf/material-ui:   Types of property 'enum' are incompatible.
@rjsf/material-ui:     Type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type[] | undefined' is not assignable to type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type[] | undefined'.
@rjsf/material-ui:       Type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type[]' is not assignable to type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type[]'.
@rjsf/material-ui:         Type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type' is not assignable to type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type'.
@rjsf/material-ui:           Type 'object' is not assignable to type 'JSONSchema7Type'.
@rjsf/material-ui:             Type '{}' is missing the following properties from type 'JSONSchema7Array': length, pop, push, concat, and 28 more.
@rjsf/material-ui: Error: /workspace/react-jsonschema-form/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx(39,7): semantic error TS2322: Type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7' is not assignable to type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7'.
@rjsf/material-ui:   Types of property 'enum' are incompatible.
@rjsf/material-ui:     Type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type[] | undefined' is not assignable to type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type[] | undefined'.
@rjsf/material-ui:       Type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type[]' is not assignable to type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type[]'.
@rjsf/material-ui:         Type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type' is not assignable to type 'import("/workspace/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type'.
@rjsf/material-ui:           Type 'object' is not assignable to type 'JSONSchema7Type'.
@rjsf/material-ui:             Type '{}' is missing the following properties from type 'JSONSchema7Array': length, pop, push, concat, and 28 more.
@rjsf/material-ui:     at error (/workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup/dist/shared/node-entry.js:5400:30)
@rjsf/material-ui:     at throwPluginError (/workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup/dist/shared/node-entry.js:11878:12)
@rjsf/material-ui:     at Object.error (/workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup/dist/shared/node-entry.js:12912:24)
@rjsf/material-ui:     at Object.error (/workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup/dist/shared/node-entry.js:12081:38)
@rjsf/material-ui:     at RollupContext.error (/workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)
@rjsf/material-ui:     at /workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24994:23
@rjsf/material-ui:     at arrayEach (/workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)
@rjsf/material-ui:     at forEach (/workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)
@rjsf/material-ui:     at printDiagnostics (/workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24967:5)
@rjsf/material-ui:     at Object.transform (/workspace/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollu
lerna ERR! npm run build exited 1 in '@rjsf/material-ui'
```

**Comment by paintedbicycle** [comment]
@HarmonicTons Did you solve your local build issue? I'm seeing the same one on a fresh git clone

cc @epicfaace

**Comment by epicfaace** [comment]
Hmm, that's strange. Can you ensure you're using node v14 and npm 6 and re-install node modules?

**Comment by paintedbicycle** [comment]
Yeah, it's weird. I just used nvm to get node 14. I destroyed my local and re-cloned, then updated npm to latest. Re-installed, rebuilt and got the same error. I'm on a Mac, Big Sur.

```
@rjsf/material-ui: (typescript) Error: /Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx(39,7): semantic error TS2322: Type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7' is not assignable to type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7'.
@rjsf/material-ui:   Types of property 'enum' are incompatible.
@rjsf/material-ui:     Type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type[] | undefined' is not assignable to type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type[] | undefined'.
@rjsf/material-ui:       Type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type[]' is not assignable to type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type[]'.
@rjsf/material-ui:         Type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type' is not assignable to type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type'.
@rjsf/material-ui:           Type 'object' is not assignable to type 'JSONSchema7Type'.
@rjsf/material-ui:             Type '{}' is missing the following properties from type 'JSONSchema7Array': length, pop, push, concat, and 28 more.
@rjsf/material-ui: Error: /Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx(39,7): semantic error TS2322: Type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7' is not assignable to type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7'.
@rjsf/material-ui:   Types of property 'enum' are incompatible.
@rjsf/material-ui:     Type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type[] | undefined' is not assignable to type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type[] | undefined'.
@rjsf/material-ui:       Type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type[]' is not assignable to type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type[]'.
@rjsf/material-ui:         Type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7Type' is not assignable to type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7Type'.
@rjsf/material-ui:           Type 'object' is not assignable to type 'JSONSchema7Type'.
@rjsf/material-ui:             Type '{}' is missing the following properties from type 'JSONSchema7Array': length, pop, push, concat, and 28 more.
@rjsf/material-ui:     at error (/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup/dist/shared/node-entry.js:5400:30)
@rjsf/material-ui:     at throwPluginError (/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup/dist/shared/node-entry.js:11878:12)
@rjsf/material-ui:     at Object.error (/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup/dist/shared/node-entry.js:12912:24)
@rjsf/material-ui:     at Object.error (/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup/dist/shared/node-entry.js:12081:38)
@rjsf/material-ui:     at RollupContext.error (/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)
@rjsf/material-ui:     at /Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24994:23
@rjsf/material-ui:     at arrayEach (/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)
@rjsf/material-ui:     at forEach (/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)
@rjsf/material-ui:     at printDiagnostics (/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24967:5)
@rjsf/material-ui:     at Object.transform (/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:29049:17)
@rjsf/material-ui: npm ERR! code 1
@rjsf/material-ui: npm ERR! path /Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui
@rjsf/material-ui: npm ERR! command failed
@rjsf/material-ui: npm ERR! command sh -c rimraf dist && tsdx build
@rjsf/material-ui: npm ERR! A complete log of this run can be found in:
```

**Comment by epicfaace** [comment]
Hmmm... looking at the error you're getting:

```
@rjsf/material-ui: (typescript) Error: /Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx(39,7): semantic error TS2322: Type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@rjsf/core/node_modules/@types/json-schema/index").JSONSchema7' is not assignable to type 'import("/Users/paintedbicycle/Sites/react-jsonschema-form/packages/material-ui/node_modules/@types/json-schema/index").JSONSchema7'.
```

Perhaps you have two different versions of `@types/json-schema` installed? Can you check the versions of `@types/json-schema` in `packages/material-ui/package-lock.json` and in `packages/core/package-lock.json`? They should match -- otherwise we might need to fix the package-lock.json files.

A better solution for the long term, though, would be to share dependencies using either `lerna bootstrap --hoist` or yarn workspaces.

**Comment by HarmonicTons** [comment]
@paintedbicycle I tried again (still on gitpod) and this time it worked. I didn't change a thing: Fresh clone, fresh dev env, node v14.16.0, npm v6.14.11.

@epicfaace in my newly working workspace the version of @types/json-schema are different in material-ui and core:
- core: @types/json-schema@7.0.4
- material-ui: @types/json-schema@7.0.3

**Comment by paintedbicycle** [comment]
@epicfaace Yup, that was it. PR here: https://github.com/rjsf-team/react-jsonschema-form/pull/2310
