### ISSUE TITLE
[bootstrap-4] [CheckboxesWidget] - `<form> cannot appear as a descendant of <form>`

### ISSUE THREAD

**Issue by kubajal** [rjsf-team/react-jsonschema-form#2355]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue. 

**Link to the JSFiddle: https://jsfiddle.net/cuq1y8n7/7/ (just copy & paste it locally)**

### Description

A minimal example of [CheckboxesWidget](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/bootstrap-4/src/CheckboxesWidget/CheckboxesWidget.tsx) from `@rjsf/bootstrap-4` causes the error: `<form> cannot appear as a descendant of <form>`.

### Steps to Reproduce

1. Create the following app:
```
import Form from "@rjsf/bootstrap-4";
[...]
const custom_schema = {
  type: "object",
  properties: {
    arrayTest: {
    	type: "array",
      items: {
      	type: "string",
        enum: ["1", "2", "3"]
      },
      uniqueItems: true
    }
  }
};
const custom_uiSchema = {
  arrayTest: {
  	"ui:widget": "checkboxes"
  }
[...]
ReactDOM.render(<Form schema={custom_schema} uiSchema={custom_uiSchema}/>, 
             document.getElementById("root"));
```
2. run the app: `npm start`

#### Expected behavior

The checkboxes should be rendered without errors.

#### Actual behavior

The checkboxes are rendered but the console reads:
```
index.js:1 Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>.
    at form
    at http://localhost:3000/static/js/vendors~main.chunk.js:50226:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:50825:23
    at CheckboxesWidget (http://localhost:3000/static/js/vendors~main.chunk.js:5438:21)
    at Widget.MergedWidget (http://localhost:3000/static/js/vendors~main.chunk.js:11115:33)
    at ArrayField (http://localhost:3000/static/js/vendors~main.chunk.js:6932:102)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:50825:23
    at FieldTemplate (http://localhost:3000/static/js/vendors~main.chunk.js:5319:17)
    at SchemaField (http://localhost:3000/static/js/vendors~main.chunk.js:8905:102)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:50037:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:51234:23
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:50107:23
    at ObjectFieldTemplate (http://localhost:3000/static/js/vendors~main.chunk.js:5345:31)
    at ObjectField (http://localhost:3000/static/js/vendors~main.chunk.js:8257:102)
    at div
    at http://localhost:3000/static/js/vendors~main.chunk.js:50825:23
    at FieldTemplate (http://localhost:3000/static/js/vendors~main.chunk.js:5319:17)
    at SchemaField (http://localhost:3000/static/js/vendors~main.chunk.js:8905:102)
    at form
    at Form (http://localhost:3000/static/js/vendors~main.chunk.js:6177:102)
    at http://localhost:3000/static/js/vendors~main.chunk.js:12559:23
```

### Version

```
"@rjsf/bootstrap-4": "^2.5.1",
"@rjsf/core": "^2.5.1",
```

**Comment by heath-freenome** [comment]
Fixed in v5 beta via #3145
