### ISSUE TITLE
Testing MUI5 Form with Jest and Typescript gives error "Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by krogerdev** [rjsf-team/react-jsonschema-form#3484]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

material-ui

### Version

5.2.0 (same with 5.1.0)

### Current Behavior

Starting Jest test stops at the component using Form from MUI5. 
Giving the following erroroutput:
```
    /home/kroger/test-projs/tester/node_modules/nanoid/index.browser.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { urlAlphabet } from './url-alphabet/index.js'
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import Form from '@rjsf/mui';
        | ^
      2 | import validator from '@rjsf/validator-ajv8';
      3 |
      4 | import { render } from '@testing-library/react';

      at Runtime.createScriptFromCode (node_modules/jest-cli/node_modules/jest-runtime/build/index.js:1495:14)
      at Object.<anonymous> (node_modules/@rjsf/core/dist/core.cjs.development.js:13:14)
      at Object.<anonymous> (node_modules/@rjsf/core/dist/index.js:7:20)
      at Object.<anonymous> (node_modules/@rjsf/mui/dist/mui.cjs.development.js:5:12)
      at Object.<anonymous> (node_modules/@rjsf/mui/dist/index.js:7:20)
      at Object.<anonymous> (src/App.test.tsx:1:1)
```

### Expected Behavior

Tests completing and actually testing the component

### Steps To Reproduce

1. Create new react app with typescript template
2. Add RJSF packages (Core, Utils, MUI and Validator-ajv8)
3. Add Jest test and set preset to "ts-jest" and testEnvironment to "jsdom" in package.json / jest config
4. Write a test that imports Form from @rjsf/mui and renders it using @testing-library/react
5. Start said test

### Environment

```markdown
- OS: Ubuntu 22.10
- Node: 16.19.1
- npm: 9.5.0
```

### Anything else?

Ive tested this both in the project Im actually testing and standalone with testing the Form from MUI directly, both resulting in the same result.
With Jest' Experimental ESM support enabled I get an error stating that I have to use import on all packages instead.
I realize this might not be the right place to ask, but this is where Im starting as its pointing out rjsf/mui as the culprit. Though I realize that its also pointing out nanoid as a culprit, but Im not using nanoid in my project outside of it being a dependency in rjsf.
I found a similar issue with core posted earlier here, but the fix that was provided here with moduleNameMapper in jest config did not work for me.

**Comment by krogerdev** [comment]
I realize now after posting and re-reading that Im making it sound like Im attempting to just test the Form component from RJSF. My goal here is to test a component in a library Im working on that uses the RJSF package to render and validate a Form. Which fails to test when it renders the Form component. 
Additional sidenote: The library and said component works as it should when built using rollup and used in other apps, its just failing when being tested with Jest.

**Comment by krogerdev** [comment]
@heath-freenome No not in any way, but urlAlphabet is something that is part of nanoid, neither nanoid or urlAlphabet is something that is used in my project outside of being a dependency in other packages I use. Since this happens only when I import Form from rjsf/mui I drew a conclusion that it is the RJSF import that triggers this.

**Comment by krogerdev** [comment]
Did the same steps mentioned above in steps to reproduce now just without the typescript template. Same error occurs.
Only difference I made in the steps was to remove `--template typescript` from the creation script

**Comment by krogerdev** [comment]
Looks like I at least have gotten past the stage of importing Form now.
 ```
"moduleNameMapper": {
      "@rjsf/mui": "<rootDir>/node_modules/@rjsf/mui/dist/mui.cjs.production.min.js",
      "nanoid": "<rootDir>/node_modules/nanoid/index.browser.cjs"
    }
```
Adding this to the jest config seems to at least allow me to import Form and render it without the beforementioned error occuring. Not sure if this is the right way to do it or if this is the right place to post, but Im gonna continue testing and see if I can write the tests for this component. If it works then this was the solution for me at least, both in typescript and javascript

**Comment by krogerdev** [comment]
> Looks like I at least have gotten past the stage of importing Form now.
> 
> ```
> "moduleNameMapper": {
>      "nanoid": "<rootDir>/node_modules/nanoid/index.browser.cjs"
>    }
> ```
> 
> Adding this to the jest config seems to at least allow me to import Form and render it without the beforementioned error occuring. Not sure if this is the right way to do it or if this is the right place to post, but Im gonna continue testing and see if I can write the tests for this component. If it works then this was the solution for me at least, both in typescript and javascript.
> 
> Edit: Only need to map nanoid. Imo this is the right place to post since Im not using nanoid anywhere directly in my project.

I dont know if this is the way to do it, but the issue was resolved. I was able to write all necessary tests using this fix. Closing this as a result.

**Comment by heath-freenome** [comment]
Hmmm, that solution makes sense. I've had to do similar things in projects for work.

**Comment by peguerosdc** [comment]
I was having the same issue but when trying to import stuff from core:

```
/Users/user/project/node_modules/nanoid/index.browser.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { urlAlphabet } from './url-alphabet/index.js'
                                                                                  ^^^^^^

SyntaxError: Cannot use import statement outside a module

  1 | import { BaseInputTemplateProps, RJSFSchema } from "@rjsf/utils";
> 2 | import { getDefaultRegistry, default as RJSFForm } from "@rjsf/core"
```

And adding the entry to `moduleNameMapper` worked for me. Thanks!
