### ISSUE TITLE
liveOmit & omitExtraData not work with empty oneOf

### ISSUE THREAD

**Issue by YuJianghao** [rjsf-team/react-jsonschema-form#4066]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.x

### Current Behavior

With both `liveOmit` and `omitExtraData` set to `true` and a field with `oneOf: []`, changing form will cause error ([playground reproduction](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJpZCI6IjEyMzEyMzEyMTIzMTIzIiwic3R5bGUiOiIyIn0sInNjaGVtYSI6eyJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJpZCI6eyJ0eXBlIjoic3RyaW5nIn0sInN0eWxlIjp7InR5cGUiOiJzdHJpbmciLCJvbmVPZiI6W119fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIiLCJ1aTpwbGFjZWhvbGRlciI6InVpOmVtcHR5VmFsdWUgY2F1c2VzIHRoaXMgZmllbGQgdG8gYWx3YXlzIGJlIHZhbGlkIGRlc3BpdGUgYmVpbmcgcmVxdWlyZWQiLCJ1aTphdXRvY29tcGxldGUiOiJmYW1pbHktbmFtZSIsInVpOmVuYWJsZU1hcmtkb3duSW5EZXNjcmlwdGlvbiI6dHJ1ZSwidWk6ZGVzY3JpcHRpb24iOiJNYWtlIHRleHQgKipib2xkKiogb3IgKml0YWxpYyouIFRha2UgYSBsb29rIGF0IG90aGVyIG9wdGlvbnMgW2hlcmVdKGh0dHBzOi8vcHJvYmFibHl1cC5jb20vbWFya2Rvd24tdG8tanN4LykuIn0sImxhc3ROYW1lIjp7InVpOmF1dG9jb21wbGV0ZSI6ImdpdmVuLW5hbWUiLCJ1aTplbmFibGVNYXJrZG93bkluRGVzY3JpcHRpb24iOnRydWUsInVpOmRlc2NyaXB0aW9uIjoiTWFrZSB0aGluZ3MgKipib2xkKiogb3IgKml0YWxpYyouIEVtYmVkIHNuaXBwZXRzIG9mIGBjb2RlYC4gPHNtYWxsPkFuZCB0aGlzIGlzIGEgc21hbGwgdGV4dHMuPC9zbWFsbD4gIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aCB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJzaG93RXJyb3JMaXN0IjoidG9wIiwidmFsaWRhdGUiOmZhbHNlLCJkaXNhYmxlZCI6ZmFsc2UsIm5vSHRtbDVWYWxpZGF0ZSI6ZmFsc2UsInJlYWRvbmx5IjpmYWxzZSwib21pdEV4dHJhRGF0YSI6dHJ1ZSwibGl2ZU9taXQiOnRydWUsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMifX19)):

```
index-90aec295.js:43 Uncaught TypeError: Cannot use 'in' operator to search for '$ref' in undefined
    at ug (index-90aec295.js:43:9733)
    at ug (index-90aec295.js:43:9972)
    at ug (index-90aec295.js:43:10407)
    at Eet (index-90aec295.js:43:10484)
    at Pet.toPathSchema (index-90aec295.js:43:11713)
    at onChange (index-90aec295.js:64:28374)
    at index-90aec295.js:64:5148
    at index-90aec295.js:64:1174
    at index-90aec295.js:64:5148
    at index-90aec295.js:64:11289
```

### Expected Behavior

change the form without error

### Steps To Reproduce

1. set both `liveOmit` and `omitExtraData` Form props to `true`
2. set a field's schema to `oneOf: []`
3. change form values through other field
4. error `Cannot use 'in' operator to search for '$ref' in undefined`

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

Maybe this line throw the error

https://github.com/rjsf-team/react-jsonschema-form/blob/d58775b444b04465a6ae01300e1f3e18e6145c95/packages/utils/src/schema/toPathSchema.ts#L41

**Comment by nickgros** [comment]
@YuJianghao This is not a valid JSON Schema per the [spec](https://json-schema.org/draft/2020-12/json-schema-core#name-oneof):
> This keyword's value MUST be a non-empty array.

We can accept a PR to handle this case and log a warning if it would improve the experience of using RJSF
