### ISSUE TITLE
AntDesign date time picker does not work

### ISSUE THREAD

**Issue by troos18** [rjsf-team/react-jsonschema-form#4305]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

antd

### Version

5.20.1

### Current Behavior

In my App, I have an issue when trying to edit a date picker field using antd.

Got this log:
```js
moment.js:24 Uncaught TypeError: clone.weekday is not a function
    at Object.getWeekDay (moment.js:24:18)
    at getWeekStartDate (dateUtil.js:101:41)
    at DateBody (DateBody.js:30:83)
    at renderWithHooks (react-dom.development.js:15486:18)
    at mountIndeterminateComponent (react-dom.development.js:20098:13)
    at beginWork (react-dom.development.js:21621:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27485:7)
```

### Expected Behavior

I should be able to edit the field.

### Steps To Reproduce

Using your [playground](https://rjsf-team.github.io/react-jsonschema-form/) with theme=antd

JSON Schema:
```json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema",
  "examples": [
    {
      "date": "2024-09-17T03:24:00"
    }
  ],
  "properties": {
    "date": {
      "type": "string",
      "title": "Date",
      "format": "date-time",
      "description": "Date and time"
    }
  }
}
```

Try to edit the field, nothing happen.

### Environment

```markdown
- OS: macOS M2 14.6.1 & Windows 10 pro 22H2
- Node: 22.8.0
- npm: 10.8.2
```

**Comment by heath-freenome** [comment]
@troos18 Thanks for the bug report. The issue is also quite visible on our [date time page](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6e30sInNjaGVtYSI6eyJ0aXRsZSI6IkRhdGUgYW5kIHRpbWUgd2lkZ2V0cyIsInR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7Im5hdGl2ZSI6eyJ0aXRsZSI6Ik5hdGl2ZSIsImRlc2NyaXB0aW9uIjoiTWF5IG5vdCB3b3JrIG9uIHNvbWUgYnJvd3NlcnMsIG5vdGFibHkgRmlyZWZveCBEZXNrdG9wIGFuZCBJRS4iLCJ0eXBlIjoib2JqZWN0IiwicHJvcGVydGllcyI6eyJkYXRldGltZSI6eyJ0eXBlIjoic3RyaW5nIiwiZm9ybWF0IjoiZGF0ZS10aW1lIn0sImRhdGUiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImRhdGUifSwidGltZSI6eyJ0eXBlIjoic3RyaW5nIiwiZm9ybWF0IjoidGltZSJ9fX0sImFsdGVybmF0aXZlIjp7InRpdGxlIjoiQWx0ZXJuYXRpdmUiLCJkZXNjcmlwdGlvbiI6IlRoZXNlIHdvcmsgb24gbW9zdCBwbGF0Zm9ybXMuIiwidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsiYWx0LWRhdGV0aW1lIjp7InR5cGUiOiJzdHJpbmciLCJmb3JtYXQiOiJkYXRlLXRpbWUifSwiYWx0LWRhdGUiOnsidHlwZSI6InN0cmluZyIsImZvcm1hdCI6ImRhdGUifX19fX0sInVpU2NoZW1hIjp7ImFsdGVybmF0aXZlIjp7ImFsdC1kYXRldGltZSI6eyJ1aTp3aWRnZXQiOiJhbHQtZGF0ZXRpbWUiLCJ1aTpvcHRpb25zIjp7InllYXJzUmFuZ2UiOlsxOTgwLDIwMzBdLCJmb3JtYXQiOiJZTUQifX0sImFsdC1kYXRlIjp7InVpOndpZGdldCI6ImFsdC1kYXRlIiwidWk6b3B0aW9ucyI6eyJ5ZWFyc1JhbmdlIjpbMTk4MCwyMDMwXSwiZm9ybWF0IjoiTURZIn19fX0sInRoZW1lIjoiYW50ZCJ9) in the playground. As we normally rely on developers to deal with theme specific issues, would you be willing to provide a fix for us?

**Comment by troos18** [comment]
Hello,
Sorry for late answer.
Unfortunately, I can't try to provide a fix for now.
Is there another way to fix this ?

**Comment by heath-freenome** [comment]
Likely not. Do you have anyone you work with who may be able to fix it?

**Comment by MaximeSauvageD4** [comment]
Hi @heath-freenome, can we have a helping hand on this please?
We've managed to display the popup of the date picker by adding a call to `<DatePicker />` from Antd under `<DemoFrame />` in `react-jsonschema-form/packages/playground/src/components/Playground.tsx`. Note that I talk about the popup of the widget.
The popup does not appearwhen the field is focused but does when the user clicks outside of it after. It stays displayed until field is focused again.

**Comment by heath-freenome** [comment]
@MaximeSauvageD4 Does the date picker popup work in an antd application outside of the playground?
