### ISSUE TITLE
Error when run in latest Remix

### ISSUE THREAD

**Issue by scottwansz** [rjsf-team/react-jsonschema-form#4364]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [X] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

validator-ajv8

### Version

5.x

### Current Behavior
I follow the react-jsonschema-form quick start with latest pure clean empty Remix project get error as below:

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6120:9)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderIndeterminateComponent (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5852:7)
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderContextProvider (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5997:3)
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6094:11)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderIndeterminateComponent (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5852:7)
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderContextProvider (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5997:3)
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6094:11)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderIndeterminateComponent (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5852:7)
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderIndeterminateComponent (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5852:7)
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderChildrenArray (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6288:7)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6218:7)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderHostElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5708:3)
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6029:5)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderChildrenArray (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6288:7)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6218:7)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderNode (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6336:12)
    at renderHostElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5708:3)
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6029:5)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderIndeterminateComponent (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5852:7)
    at renderElement (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6023:7)
    at renderNodeDestructiveImpl (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6181:11)
    at renderNodeDestructive (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:6153:14)
    at renderContextProvider (C:\Users\scott\Desktop\remix-rjsf-demo\node_modules\.pnpm\react-dom@18.3.1_react@18.3.1\node_modules\react-dom\cjs\react-dom-server.node.development.js:5997:3)

### Environment

```markdown
- OS: Windows 11
- Node: node/21.1.0/x64
- pnpm: 8.15.5
```

### Anything else?

the remix project I created by "npx create-vite" then select remix.

_No response_

**Comment by nickgros** [comment]
@scottwansz Can you provide a CodeSandbox example?

**Comment by scottwansz** [comment]
> @scottwansz Can you provide a CodeSandbox example?

https://codesandbox.io/p/devbox/sweet-heisenberg-kllcft?workspaceId=c60c87b7-3dc6-4512-919b-c4253f32ff10

**Comment by nickgros** [comment]
@scottwansz Sorry, I get a "not found" error when I try to open that link

**Comment by scottwansz** [comment]
> @scottwansz Sorry, I get a "not found" error when I try to open that link

sorry, i forget change the permmission, now you access.

**Comment by nickgros** [comment]
For some reason SSR is not working. As a workaround you can do CSR, e.g.

```tsx
  const [isClient, setIsClient] = useState(false)
  useEffect(() => {
    setIsClient(true)
  }, [])
  return (<>
    {isClient && (<Form {...props} />)}
  </>)
```

Here's a similar issue: #4083

Us maintainers don't have the bandwidth to dive in deep for every issue, so any help pinpointing the bug would be appeciated.

**Comment by Sutikshan** [comment]
Thanks @nickgros , Above way, I am able to use RJSF with Remix SSR.
With growing usage of SSR, I hope we will find a way. Another issue I faced with Vite was while importing stuff from @rjsf/utils
I was getting an error which I fixed by importing from it in following way


```
import * as RjSfUtils from '@rjsf/utils';

const { descriptionId, schemaRequiresTrueValue, getTemplate } = RjSfUtils;
```

**Comment by heath-freenome** [comment]
> Thanks [@nickgros](https://github.com/nickgros) , Above way, I am able to use RJSF with Remix SSR. With growing usage of SSR, I hope we will find a way. Another issue I faced with Vite was while importing stuff from @rjsf/utils I was getting following error :
> 
> `The requested module '@rjsf/utils' is a CommonJS module, which may not support all module.exports as named exports.`
> 
> which I fixed by importing from it in following way
> 
> ```
> import * as RjSfUtils from '@rjsf/utils';
> 
> const { descriptionId, schemaRequiresTrueValue, getTemplate } = RjSfUtils;
> ```

With v6 we have full ESM support now. So this should no longer be an issue in vite

**Comment by heath-freenome** [comment]
@scottwansz Can you try your codesandbox with 6.x? I tried updating it locally but it kept causing errors for me
